version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my-sql
    environment:
      MYSQL_DATABASE: microservice
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    hostname: axonserver
    ports:
      - "8024:8024"   # gRPC port
      - "8124:8124"   # HTTP port
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    networks:
      - axon-network

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - myNetwork

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - myNetwork
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    container_name: redis-vendor
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "16379:6379"
networks:
  axon-network:
    driver: bridge
  myNetwork:
    driver: bridge

volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  mysql-data:
  redis.conf:
  kafka:
  zookeeper_data:
  zookeeper_log:
