spring:
  application:
    name: manage
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: root
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_updates: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 5000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      group-id-1: 'account'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer-group:
      group-push: 'account'


server:
  port: 9093

jwt:
  secret: anhpd_130398_!@#$!@#!!!123_api_config_authentication


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      eureka-server-retry-attempts: 2
#    registry-fetch-interval-seconds: 10    # Khoảng thời gian giữa các yêu cầu fetch registry
#    initial-instance-info-replication-interval-seconds: 5
#    eureka-server-connect-timeout-seconds: 5  # Timeout khi kết nối đến Eureka
#    eureka-server-read-timeout-seconds: 8     # Timeout khi đọc dữ liệu từ Eureka
#    healthcheck:
#      enabled: true
#  instance:
#    # Khoảng thời gian giữa các lần gia hạn lease với Eureka
#    lease-renewal-interval-in-seconds: 10
#    # Khoảng thời gian client sẽ được đánh dấu là DOWN nếu không gia hạn
#    lease-expiration-duration-in-seconds: 30

