server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # Cho phép tất cả các đường dẫn
            allowedOrigins: "http://localhost:9091, http://localhost:9093"  # Các nguồn được phép
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      #            allowCredentials: true
      discovery:
        locator:
          enabled: true
jwt:
  secret: anhpd_130398_!@#$!@#!!!123_api_config_authentication

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: auth
        url: http://localhost:9091/v3/api-docs
      - name: manage
        url: http://localhost:9093/v3/api-docs
  cache:
    disabled: true



microservices:
  employee:
    secret-key: employee
    uri: /api/employee