server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: secret_key_for_my_personal_e_commerce_project

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
#  group-configs:
#    - group: auth
#      paths-to-match: /auth/**
#    - group: employee
#      paths-to-match: /api/employee/**
#    - group: order
#      paths-to-match: /order/**
#    - group: shipping
#      paths-to-match: /shipping/**
#    - group: vendor
#      paths-to-match: /vendor/**
#    - group: image
#      paths-to-match: /file/**