spring:
  application:
   name: shipping
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
#      value-deserializer: org.service.shipping.events.ShipmentDeserializer
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    listener:
      ack-mode: MANUAL
      missing-topics-fatal: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9095
