spring:
  application:
    name: shipping
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
#      group-id-1: 'order'
      enable-auto-commit: false
      max-poll-records: 2
      group-id: 'order'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

#    listener:
#      change-consumer-thread-name: true
#      concurrency: 3
#    client-id: spring-kafka-demo

server:
  port: 9095