spring:
  application:
    name: image
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
     enabled: true
     max-file-size: 10MB
     max-request-size: 10MB
  profiles:
    active: local

server:
  port: 9098


jwt:
  secret: secret_key_for_my_personal_e_commerce_project


image:
  url: "http://localhost:9090"
