spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 9091

jwt:
  secret: VGhpc19pc19zZWNyZXRfa2V5X3ZhbGlkX3Rva2VuX2Zvcl9wcm9qZWN0
  expiration: 3600000
  expiration-refresh: 3900000

#axon:
#  axonserver:
#    servers: localhost:8024

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  cache:
    disabled: true