spring:
  application:
    name: auth

  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_schema: "microservice"
  flyway:
    enabled: false



#  kafka:
#    #    admin:
#    #      properties:
#    #        num.partition: 3
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    producer-group:
#      group-push: 'account'
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      auto-offset-reset: earliest
#      group-id-1: 'account'

server:
  port: 9091

jwt:
  secret: anhpd_130398_!@#$!@#!!!123_api_config_authentication
  expiration: 3600000
  expiration-refresh: 3900000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#      eureka-server-retry-attempts: 2
#    registry-fetch-interval-seconds: 10    # Khoảng thời gian giữa các yêu cầu fetch registry
#    initial-instance-info-replication-interval-seconds: 5
#    eureka-server-connect-timeout-seconds: 5  # Timeout khi kết nối đến Eureka
#    eureka-server-read-timeout-seconds: 8     # Timeout khi đọc dữ liệu từ Eureka
#    healthcheck:
#      enabled: true
#  instance:
#    # Khoảng thời gian giữa các lần gia hạn lease với Eureka
#    lease-renewal-interval-in-seconds: 10
#    # Khoảng thời gian client sẽ được đánh dấu là DOWN nếu không gia hạn
#    lease-expiration-duration-in-seconds: 30



axon:
  axonserver:
    servers: localhost:8024
    ssl-enabled: false


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  cache:
    disabled: true