spring:
  application:
    name: syncdb
  datasource:
    mysql:
      url: jdbc:mysql://localhost:13306/microservice
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://localhost:5432/microservice
      username: root
      password: 123456789
      driver-class-name: org.postgresql.Driver


server:
  port: 9098


