spring:
  application:
    name: employee
  kafka:
#    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
#      value-deserializer: com.ngoctuan.shipping.events.ShipmentDeserializer
#      auto-offset-reset: earliest
#      enable-auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 9093

jwt:
  secret: secretPD*!@#$$$$$$$$$123131231eeee@@@##$!$!%$^$%&*%^*$%^@$%


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
  cache:
    disabled: true