spring:
  application:
    name: bath
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    mysql:
      url: jdbc:mysql://localhost:13306/microservice
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    aws:
      credentials:
        access-key: AKIASAYNBK5GPTFRRRNN
        secret-key: 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
      region:
        static: ap-southeast-2
      bucket:
        name: anhpd
#      endpoint: https://anhpd.s3.ap-southeast-2.amazonaws.com



server:
  port: 9099


batch:
  max-record: 5000
  cron: 0 * */8 * * *


