spring:
  application:
    name: bath
  #  main:
  #    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    mysql:
      url: jdbc:mysql://localhost:13306/microservice
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgres:
      url: jdbc:postgresql://localhost:5432/microservice
      username: root
      password: 123456789
      driver-class-name: org.postgresql.Driver
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    import: optional:aws-secretsmanager:${AWS_S3_SECRET_MANGER}
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        endpoint: ${AWS_S3_URL:https://anhpd.s3.ap-southeast-2.amazonaws.com}
        region: ap-southeast-2
        bucket: anhpd
        enabled: true
server:
  port: 9099
  forward-headers-strategy: framework


batch:
  max-record: 5000
  cron: 0 * */8 * * *