spring:
  application:
    name: elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
#    password: wJP-ERRVFeNVbnwFDhW1


  datasource:
    url: jdbc:mysql://localhost:13306/microservice
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9096

jwt:
  secret: anhpd_130398_!@#$!@#!!!123_api_config_authentication


